### ISSUE TITLE
Connect z-axis sensor

### ISSUE THREAD

**Issue by AlexandrSminrov** [jojos38/anycubic-kobra-skr-3-ez-firmware#1]
Hi!
I'm trying to repeat your build with a default extruder.
How did you connect the inductive z-axis sensor?
Is there a guide somewhere on the changing from trigorilla pro to btt skr3 ez?

**Comment by jojos38** [comment]
> Hi! I'm trying to repeat your build with a default extruder. How did you connect the inductive z-axis sensor? Is there a guide somewhere on the changing from trigorilla pro to btt skr3 ez?

Hey, sorry for the late reply, for the probe it's a pain to do so, basically you have two solutions:
- Solution 1: Remove the daughterboard and create a circuit yourself, it needs to output 5V or 0V depending if the probe is triggered or not
- Solution 2: Keep the daughterboard and add a pullup resistor between the 5V and GND of the probe, you also need a decoupling capacitor if you want it to work better than it originally does

I can't give more details because I don't remember exactly what I did but it may help you, if you don't have any knowledge about electronic the best solution is probably to change to another ABL

For the motherboard it's annoying but doable, you simply have to reroute all the cables and crimp new connectors on each of them. The SKR EZ 3 comes with all its connectors so it's pretty handy, it just takes a lot of time you need to be patient
